# Generated by Django 5.0.4 on 2024-04-22 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_account_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='phone_number',
        ),
    ]
