# Generated by Django 5.0.4 on 2024-04-19 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(choices=[('Computers and Laptops', 'Computers and Laptops'), ('Peripherals and Accessories', 'Peripherals and Accessories'), ('Components and Parts', 'Components and Parts'), ('Mobile Devices and Accessories', 'Mobile Devices and Accessories')], max_length=100),
        ),
    ]
