# Generated by Django 5.0.4 on 2024-04-20 21:15

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_image',
            field=models.ImageField(default='B00318CGIC-2.jpg', upload_to=products.models.get_image_upload),
        ),
    ]
