# Generated by Django 5.0.4 on 2024-04-21 08:50

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_category_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_image',
            field=models.ImageField(upload_to=products.models.get_image_upload),
        ),
    ]
